name: Docker Publishing

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:

    # runs-on is not the same as base image. Upgrade to 20.04?
    runs-on: ubuntu-18.04

    # Build the two images *sequentially*.
    # `pcic/pdp-base-with-pg9.3` is based on `pcic/pdp-base-minimal`.
    steps:
      - uses: actions/checkout@master

      - name: Publish pdp-base-minimal to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: base-minimal.Dockerfile
          repository: pcic/pdp-base-minimal
          tag_with_ref: true

      - name: Publish pdp-base-with-pg9.3 to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: base-with-pg9.3.Dockerfile
          repository: pcic/pdp-base-with-pg9.3
          tag_with_ref: true

      - name: Publish pdp-UNSAFE-base-minimal to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: UNSAFE-base-minimal.Dockerfile
          repository: pcic/pdp-UNSAFE-base-minimal
          tag_with_ref: true
